Linux build:

  stage: build

  script:
  - export DISPLAY=mespak3.cs.ucl.ac.uk:1
  - export NIFTK_DRC_ANALYZE=ON
  - src_dir=`pwd`
  - ep_dir="/home/gitlab-runner/src/NiftyMIDAS-ep"
  - mkdir -p ${ep_dir}
  - /home/gitlab-runner/bin/niftk-ep-clean-up.sh ${src_dir} ${ep_dir} &
  - hostname
  - whoami
  - pwd
  - cd ..
  - rm -rf NiftyMIDAS-sb
  - mkdir NiftyMIDAS-sb
  - cd NiftyMIDAS-sb
  - cmake -DEP_BASE:PATH=${ep_dir}
        -DEP_ALWAYS_USE_INSTALL_DIR:BOOL=FALSE -DEP_DIRECTORY_PER_VERSION:BOOL=TRUE
        -DBUILD_TESTING:BOOL=ON
        -DNIFTK_USE_CPPCHECK:BOOL=TRUE -DNIFTK_USE_KWSTYLE:BOOL=ON
        ../NiftyMIDAS
  - make -j 8

  except:
  - tags

  tags:
  - linux


Linux test:

  stage: test

  script:
  - export DISPLAY=mespak3.cs.ucl.ac.uk:1
  - export NIFTK_DRC_ANALYZE=ON
  - hostname
  - whoami
  - pwd
  - cd ../NiftyMIDAS-sb/NifTK-build
  - ctest -S CTestContinuous.cmake -V

  except:
  - tags

  tags:
  - linux


Mac build:

  stage: build

  script:
  - export DISPLAY=mespak3.cs.ucl.ac.uk:1
  - export NIFTK_DRC_ANALYZE=ON
  - src_dir=`pwd`
  - ep_dir="/Users/gitlab-runner/src/NiftyMIDAS-ep"
  - mkdir -p ${ep_dir}
  - /Users/gitlab-runner/bin/niftk-ep-clean-up.sh ${src_dir} ${ep_dir} &
  - hostname
  - whoami
  - pwd
  - cd ..
  - rm -rf NiftyMIDAS-sb
  - mkdir NiftyMIDAS-sb
  - cd NiftyMIDAS-sb
  - cmake -DEP_BASE:PATH=${ep_dir}
        -DEP_ALWAYS_USE_INSTALL_DIR:BOOL=FALSE -DEP_DIRECTORY_PER_VERSION:BOOL=TRUE
        -DBUILD_TESTING:BOOL=ON
        ../NiftyMIDAS
  - make -j 8

  except:
  - tags

  tags:
  - mac


Mac test:

  stage: test

  script:
  - export NIFTK_DRC_ANALYZE=ON
  - hostname
  - whoami
  - pwd
  - cd ../NiftyMIDAS-sb/NifTK-build
  - ctest -S CTestContinuous.cmake -V

  except:
  - tags

  tags:
  - mac


Windows build:

  stage: build

  script:
  - "@echo off"
  - hostname
  - '"C:\CB\slowrunner.exe" -v -2 -e "c:\CB\NiftyMIDASContinuousBuild.bat"'
  - "@exit /b %errorlevel%"

  except:
  - tags

  tags:
  - windows


Windows test:

  stage: test

  script:
  - set NIFTK_DRC_ANALYZE ON
  - hostname
  - pwd
  - cd NifTK-build
  - ctest -S CTestContinuous.cmake -V

  tags:
  - windows

  except:
  - tags


Docs:

  stage: deploy

  script:
  - cd ../niftk-sb/NifTK-build
  - chmod a+rx bin/GenerateCommandLineDoxygen
  - bin/GenerateCommandLineDoxygen
  - chmod a+rx bin/GenerateTestingReports
  - bin/GenerateTestingReports
  - doxygen doxygen.config
  - NIFTK_VERSION=`grep "NIFTK_VERSION_STRING:STRING" CMakeCache.txt | cut -c 29-`
  - echo "${NIFTK_VERSION}"
  - cd Doxygen
  - rm -rf niftk-current-docs
  - mv ${NIFTK_VERSION}/html niftk-current-docs
  - find . -type f -exec chmod 644 {} \;
  - find . -type d -exec chmod 755 {} \;
  - tar cfj niftk-current-docs.tar.bz2 niftk-current-docs
  - echo "API reference documentation generated:"
  - echo `pwd`/niftk-current-docs.tar.bz2
  - "# Delete the previous tarball"
  - ssh cmiclab rm -f /cs/research/medic/cmiclab/gitlab/deploy/CMIC/NifTK/docs/niftk-current-docs.tar.bz2
  - "# Upload the tarball"
  - scp niftk-current-docs.tar.bz2 cmiclab:/cs/research/medic/cmiclab/gitlab/deploy/CMIC/NifTK/docs/niftk-current-docs.tar.bz2
  - "# Extract the tarball and replace the old files"
  - ssh cmiclab "cd /cs/research/medic/cmiclab/gitlab/deploy/CMIC/NifTK/docs ; tar
    xvfj niftk-current-docs.tar.bz2 ; mv current tmp ; mv niftk-current-docs current
    ; rm -rf tmp"

  only:
  - master
  - dev

  tags:
  - linux
