Linux:
  script:
  - src_dir=`pwd`
  - ep_dir="/home/gitlab-runner/src/niftk-ep"
  - hostname
  - cd ..
  - rm -rf niftk-sb
  - mkdir niftk-sb
  - cd niftk-sb
  - cmake -DEP_BASE:PATH=${ep_dir}
        -DEP_ALWAYS_USE_INSTALL_DIR:BOOL=FALSE -DEP_DIRECTORY_PER_VERSION:BOOL=TRUE
        -DBUILD_TESTING:BOOL=ON
        -DNIFTK_USE_CPPCHECK:BOOL=TRUE -DNIFTK_USE_KWSTYLE:BOOL=ON
        -DNIFTK_Apps/NiftyView:BOOL=ON -DNIFTK_Apps/NiftyIGI:BOOL=ON
        ../NifTK
  - make -j 8
  - cd NifTK-build
  - ctest -S CTestContinuous.cmake -V
  - /home/gitlab-runner/bin/niftk-ep-clean-up.sh ${src_dir} ${ep_dir}

  tags:
  - linux

  except:
  - tags

Mac:
  script:
  - src_dir=`pwd`
  - ep_dir="/Users/gitlab-runner/src/niftk-ep"
  - hostname
  - cd ..
  - rm -rf niftk-sb
  - mkdir niftk-sb
  - cd niftk-sb
  - cmake -DEP_BASE:PATH=${ep_dir}
        -DEP_ALWAYS_USE_INSTALL_DIR:BOOL=FALSE -DEP_DIRECTORY_PER_VERSION:BOOL=TRUE
        -DBUILD_TESTING:BOOL=ON
        -DNIFTYLINK_CHECK_COVERAGE=ON
        -DNIFTK_Apps/NiftyView:BOOL=ON -DNIFTK_Apps/NiftyIGI:BOOL=ON
        ../NifTK
  - make -j 8
  - cd NifTK-build
  - ctest -S CTestContinuous.cmake -V
  - /Users/gitlab-runner/bin/niftk-ep-clean-up.sh ${src_dir} ${ep_dir}

  tags:
  - mac

  except:
  - tags

Windows:
  script:
  - "@echo off"
  - ''
  - hostname
  - ''
  - '"C:\CB\slowrunner.exe" -v -2 -e "c:\CB\NifTKContinuousBuild.bat"'
  - ''
  - "@exit /b %errorlevel%"

  tags:
  - windows

  except:
  - tags

docs:
  script:
  - cd ../niftk-sb/NifTK-build
  - ''
  - chmod a+rx bin/GenerateCommandLineDoxygen
  - bin/GenerateCommandLineDoxygen
  - ''
  - chmod a+rx bin/GenerateTestingReports
  - bin/GenerateTestingReports
  - ''
  - doxygen doxygen.config
  - ''
  - NIFTK_VERSION=`grep "NIFTK_VERSION_STRING:STRING" CMakeCache.txt | cut -c 29-`
  - echo "${NIFTK_VERSION}"
  - cd Doxygen
  - rm -rf niftk-current-docs
  - mv ${NIFTK_VERSION}/html niftk-current-docs
  - find . -type f -exec chmod 644 {} \;
  - find . -type d -exec chmod 755 {} \;
  - tar cfj niftk-current-docs.tar.bz2 niftk-current-docs
  - ''
  - echo "API reference documentation generated:"
  - echo `pwd`/niftk-current-docs.tar.bz2
  - ''
  - "# Delete the previous tarball"
  - ssh cmiclab rm -f /cs/research/medic/cmiclab/gitlab/deploy/CMIC/NifTK/docs/niftk-current-docs.tar.bz2
  - ''
  - "# Upload the tarball"
  - scp niftk-current-docs.tar.bz2 cmiclab:/cs/research/medic/cmiclab/gitlab/deploy/CMIC/NifTK/docs/niftk-current-docs.tar.bz2
  - ''
  - "# Extract the tarball and replace the old files"
  - ssh cmiclab "cd /cs/research/medic/cmiclab/gitlab/deploy/CMIC/NifTK/docs ; tar
    xvfj niftk-current-docs.tar.bz2 ; mv current tmp ; mv niftk-current-docs current
    ; rm -rf tmp"

  type: deploy

  tags:
  - linux

  only:
  - master
  - dev
