##########################################
# Jobs for continuous testing
##########################################


Linux continuous build:

  stage: build

  script:
  - export DISPLAY=mespak3.cs.ucl.ac.uk:1
  - export NIFTK_DRC_ANALYZE=ON
  - src_dir=`pwd`
  - cd ..
  - root_dir=`pwd`
  - ep_dir="${root_dir}/NiftyMIDAS-ep"
  - sb_dir="${root_dir}/NiftyMIDAS-sb"
  - pb_dir="${sb_dir}/NifTK-build"
  - /home/gitlab-runner/bin/niftk-ep-clean-up.sh ${src_dir} ${ep_dir} &
  - hostname
  - whoami
  - pwd
  - rm -rf ${sb_dir}
  - mkdir ${sb_dir}
  - cd ${sb_dir}
  - cmake -DEP_BASE:PATH=${ep_dir}
        -DEP_ALWAYS_USE_INSTALL_DIR:BOOL=OFF
        -DEP_DIRECTORY_PER_VERSION:BOOL=ON
        -DBUILD_TESTING:BOOL=ON
        -DNIFTK_USE_CPPCHECK:BOOL=ON
        -DNIFTK_USE_KWSTYLE:BOOL=ON
        -DNIFTK_Apps/NiftyMIDAS:BOOL=ON
        ${src_dir}
  - make -j 8

  only:
  - branches

  tags:
  - linux, continuous


Linux continuous test:

  stage: test

  script:
  - export DISPLAY=mespak3.cs.ucl.ac.uk:1
  - export NIFTK_DRC_ANALYZE=ON
  - cd ..
  - root_dir=`pwd`
  - sb_dir="${root_dir}/NiftyMIDAS-sb"
  - pb_dir="${sb_dir}/NifTK-build"
  - hostname
  - whoami
  - pwd
  - cd ${pb_dir}
  - ctest -S CTestContinuous.cmake -V

  only:
  - branches

  tags:
  - linux, continuous


Mac continuous build:

  stage: build

  script:
  - export DISPLAY=mespak3.cs.ucl.ac.uk:1
  - export NIFTK_DRC_ANALYZE=ON
  - src_dir=`pwd`
  - cd ..
  - root_dir=`pwd`
  - ep_dir="${root_dir}/NiftyMIDAS-ep"
  - sb_dir="${root_dir}/NiftyMIDAS-sb"
  - pb_dir="${sb_dir}/NifTK-build"
  - /Users/gitlab-runner/bin/niftk-ep-clean-up.sh ${src_dir} ${ep_dir} &
  - hostname
  - whoami
  - pwd
  - rm -rf ${sb_dir}
  - mkdir ${sb_dir}
  - cd ${sb_dir}
  - cmake -DEP_BASE:PATH=${ep_dir}
        -DEP_ALWAYS_USE_INSTALL_DIR:BOOL=OFF
        -DEP_DIRECTORY_PER_VERSION:BOOL=ON
        -DBUILD_TESTING:BOOL=ON
        -DNIFTK_Apps/NiftyMIDAS:BOOL=ON
        ${src_dir}
  - make -j 8

  only:
  - branches

  tags:
  - mac, continuous


Mac continuous test:

  stage: test

  script:
  - export NIFTK_DRC_ANALYZE=ON
  - src_dir=`pwd`
  - cd ..
  - root_dir=`pwd`
  - sb_dir="${root_dir}/NiftyMIDAS-sb"
  - pb_dir="${sb_dir}/NiftyMIDAS-build"
  - hostname
  - whoami
  - pwd
  - cd ${pb_dir}
  - ctest -S CTestContinuous.cmake -V

  only:
  - branches

  tags:
  - mac, continuous


Windows continuous build:

  stage: build

  script:
  - "@echo off"
  - hostname
  - '"C:\CB\slowrunner.exe" -v -2 -e "c:\CB\NiftyMIDASContinuousBuild.bat"'
  - "@exit /b %errorlevel%"

  only:
  - branches

  tags:
  - windows, continuous


Windows continuous test:

  stage: test

  script:
  - set NIFTK_DRC_ANALYZE ON
  - hostname
  - whoami
  - cd
  - rem cd NifTK-build
  - rem ctest -S CTestContinuous.cmake -V

  only:
  - branches

  tags:
  - windows, continuous


##########################################
# Deploy development documentation pages
##########################################


Continuous docs:

  stage: deploy

  script:
  - version=`git describe`
  - src_dir=`pwd`
  - cd ..
  - root_dir=`pwd`
  - sb_dir="${root_dir}/NiftyMIDAS-sb"
  - pb_dir="${sb_dir}/NifTK-build"
  - cd ${pb_dir}
  - rm -rf Doxygen/html
  - chmod a+rx bin/GenerateCommandLineDoxygen
  - bin/GenerateCommandLineDoxygen
  - chmod a+rx bin/GenerateTestingReports
  - bin/GenerateTestingReports
  - doxygen doxygen.config
  - cd Doxygen
  - find html -type f -exec chmod 644 {} \;
  - find html -type d -exec chmod 755 {} \;
  - rm -rf niftymidas-${version}-docs
  - mv html niftymidas-${version}-docs
  - tar cfj niftymidas-${version}-docs.tar.bz2 niftymidas-${version}-docs
  - echo "API reference documentation generated:"
  - "# Upload the tarball"
  - scp niftymidas-${version}-docs.tar.bz2 cmiclab:/cs/research/medic/cmiclab/gitlab/deploy/CMIC/NiftyMIDAS/docs/
  - "# Extract the tarball and replace the old files"
  - ssh cmiclab "cd /cs/research/medic/cmiclab/gitlab/deploy/CMIC/NiftyMIDAS/docs ;
        rm -rf `readlink -f niftymidas-current-docs.tar.bz2` `readlink -f current` ;
        rm niftymidas-current-docs current ;
        tar xfj niftymidas-${version}-docs.tar.bz2 ;
        ln -s niftymidas-${version}-docs.tar.bz2 niftymidas-current-docs.tar.bz2 ;
        ln -s niftymidas-${version}-docs current"

  only:
  - master
  - dev

  tags:
  - linux, continuous


##########################################
# Jobs for deploying tagged releases
##########################################


# Linux build for tagged versions.
# Full clean build with all the external projects, without testing and with Python.
Linux release build:

  stage: build

  script:
  - src_dir=`pwd`
  - cd ..
  - root_dir=`pwd`
  - sb_dir="${root_dir}/NiftyMIDAS-sb"
  - pb_dir="${sb_dir}/NifTK-build"
  - hostname
  - whoami
  - pwd
  - rm -rf ${sb_dir}
  - mkdir ${sb_dir}
  - cd ${sb_dir}
  - cmake -DBUILD_TESTING:BOOL=OFF
        -DNIFTK_USE_CPPCHECK:BOOL=OFF
        -DNIFTK_USE_KWSTYLE:BOOL=OFF
        -DBUILD_Python:BOOL=ON
        -DNIFTK_Apps/NiftyMIDAS:BOOL=ON
        ${src_dir}
  - make -j 8

  only:
  - tags

  tags:
  - linux, release


# Mac build for tagged versions.
# Full clean build with all the external projects, without testing and with Python.
Mac release build:

  stage: build

  script:
  - src_dir=`pwd`
  - cd ..
  - root_dir=`pwd`
  - sb_dir="${root_dir}/NiftyMIDAS-sb"
  - pb_dir="${sb_dir}/NifTK-build"
  - hostname
  - whoami
  - pwd
  - rm -rf ${sb_dir}
  - mkdir ${sb_dir}
  - cd ${sb_dir}
  - cmake -DBUILD_TESTING:BOOL=OFF
        -DNIFTK_USE_CPPCHECK:BOOL=OFF
        -DNIFTK_USE_KWSTYLE:BOOL=OFF
        -DBUILD_Python:BOOL=ON
        -DNIFTK_Apps/NiftyMIDAS:BOOL=ON
        ${src_dir}
  - make -j 8

  only:
  - tags

  tags:
  - mac, release


# Generating documentation pages for tagged releases
Release docs:

  stage: deploy

  script:
  - version=`git describe`
  - src_dir=`pwd`
  - cd ..
  - root_dir=`pwd`
  - sb_dir="${root_dir}/NiftyMIDAS-sb"
  - pb_dir="${sb_dir}/NifTK-build"
  - cd ${pb_dir}
  - rm -rf Doxygen/html
  - chmod a+rx bin/GenerateCommandLineDoxygen
  - bin/GenerateCommandLineDoxygen
  - doxygen doxygen.config
  - cd Doxygen
  - find html -type f -exec chmod 644 {} \;
  - find html -type d -exec chmod 755 {} \;
  - rm -rf niftymidas-${version}-docs
  - mv html niftymidas-${version}-docs
  - tar cfj niftymidas-${version}-docs.tar.bz2 niftymidas-${version}-docs
  - echo "API reference documentation generated:"
  - "# Upload the tarball"
  - scp niftymidas-${version}-docs.tar.bz2 cmiclab:/cs/research/medic/cmiclab/gitlab/deploy/CMIC/NiftyMIDAS/docs/
  - "# Extract the tarball and replace the old files"
  - ssh cmiclab "cd /cs/research/medic/cmiclab/gitlab/deploy/CMIC/NiftyMIDAS/docs ;
        tar xfj niftymidas-${version}-docs.tar.bz2"

  only:
  - tags

  tags:
  - linux, release


Linux release installer:

  stage: deploy

  script:
  - version=`git describe`
  - src_dir=`pwd`
  - cd ..
  - root_dir=`pwd`
  - sb_dir="${root_dir}/NiftyMIDAS-sb"
  - pb_dir="${sb_dir}/NifTK-build"
  - cd ${pb_dir}
  - niftymidas_version_string=`grep "NIFTK_VERSION_STRING:STRING" CMakeCache.txt | cut -c 29-`
  - make package
  - installer_file="niftymidas-${version}-linux-centos-7-x64.tar.gz"
  - mv niftymidas-${niftk_version_string}.tar.gz ${installer_file}
  - "# Upload the tarball"
  - scp ${installer_file} cmiclab:/cs/research/medic/cmiclab/gitlab/deploy/CMIC/NiftyMIDAS/install/

  only:
  - tags

  tags:
  - linux, release


Mac release installer:

  stage: deploy

  script:
  - version=`git describe`
  - src_dir=`pwd`
  - cd ..
  - root_dir=`pwd`
  - sb_dir="${root_dir}/NiftyMIDAS-sb"
  - pb_dir="${sb_dir}/NifTK-build"
  - cd ${pb_dir}
  - niftk_version_string=`grep "NIFTK_VERSION_STRING:STRING" CMakeCache.txt | cut -c 29-`
  - make package
  - installer_file="niftymidas-${version}-mac-10.10.dmg"
  - mv niftymidas-${niftk_version_string}.dmg ${installer_file}
  - "# Upload the installer image"
  - scp ${installer_file} cmiclab:/cs/research/medic/cmiclab/gitlab/deploy/CMIC/NiftyMIDAS/install/

  only:
  - tags

  tags:
  - mac, release
